{
  "name": "Neon",
  "version": "${version}",
  "description": "Browse the internet in Minecraft!",
  "authors": [
    "PulseBeat02"
  ],
  "api-version": "1.20",
  "main": "io.github.pulsebeat02.neon.Neon",
  "load": "STARTUP",
  "libraries": [
    "me.friwi:jcefmaven:110.0.25",
    "com.moandjiezana.toml:toml4j:0.7.2",
    "com.github.stefvanschie.inventoryframework:IF:0.10.10",
    "me.lucko:commodore:2.2",
    "org.apache.commons:commons-compress:1.23.0"
  ]
}
