{
  "name": "Neon",
  "version": "1.0.0",
  "description": "Browse the internet in Minecraft!",
  "authors": [
    "PulseBeat02"
  ],
  "api-version": "1.20",
  "main": "io.github.pulsebeat02.neon.Neon",
  "load": "STARTUP",
  "libraries": [
    "com.moandjiezana.toml:toml4j:0.7.2",
    "com.github.stefvanschie.inventoryframework:IF:0.10.11",
    "me.lucko:commodore:2.2",
    "org.seleniumhq.selenium:selenium-java:4.12.1",
    "dev.dbassett:skullcreator:3.0.1"
  ]
}
