#!/bin/bash
PWD=$(pwd)
NEON_BASE=$PWD/plugins/Neon/packages
cd $NEON_BASE
cd lib
files=(*)
FOLDER_NAME=`echo "$files"`
FIRST_SEARCH=$NEON_BASE/lib/$FOLDER_NAME
SECOND_SEARCH=$NEON_BASE/usr/lib/$FOLDER_NAME
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$FIRST_SEARCH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SECOND_SEARCH

cd $SECOND_SEARCH
ln -s "libatk-1.0.so.0.23809.1" "libatk-1.0.so.0"

echo $LD_LIBRARY_PATH

cd "../../../../jcef-bundle"
./jcef_helper